spring.application.name=course-jpa-example

# data source configuration
spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce
spring.datasource.username=root
spring.datasource.password=Mohtashim
#spring.datasource.driver-class-name=com.mysql.jdbc.cj.Driver -> optional

#we make these both below properties false  in production 99 percent times
spring.jpa.show-sql=true
#this will format the queries
spring.jpa.properties.hibernate.format_sql=true


#it will create the tables automatically -> useful if we only have mapping not the tables
#it will create the schema automatically -> but issue if we run application it create and once application is turn off-> it deletes the schema
#spring.jpa.hibernate.ddl-auto=create

#so we use update -> create the schema if necessary
# we have validate also for checking only
#if we dont want schema mapping by jpa write null
#update will modify the schema but did not drop anything
#create -> create the schema everytime the application starts
#create-drop -> if we want to create and want to drop when app shut down
spring.jpa.hibernate.ddl-auto=update

#dialect -> dialect refers to the specific sql variant  that hibernate user to interact with a particular database
#each database has its own syntax feature and hibernate uses dialect to generate database -specific sql commands
#every database has its own dialect
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect -> automatically the program will take this


